name: Upload component to production registry

on:
  push:
    tags:
      - v*

jobs:
  upload_components:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Upload component to the production registry
        uses: espressif/upload-components-ci-action@v2
        with:
          components: |
            edgeimpulse-inference-sdk: .
          skip_pre_release: true
          namespace: ozanoner